### ISSUE TITLE
Missing translation inspection cache bug

### ISSUE THREAD

**Issue by samdark** [kalessil/yii2inspections#24] opened 2017-06-02 14:49 UTC
1. Run missing translations inspection on a project A where translation are missing.
2. Switch to project B.
3. Run missing translations inspection on a project B.
4. Issues from project A are reported. Quickfix adds missing translations from totally unrelated project.

**Comment by kalessil** [comment] 2017-06-02 17:00
I need some input:
- Which PhpStorm is it?
- How do you switch between them (reopen, switch window or this probably multiple projects in one window)?

**Comment by samdark** [comment] 2017-06-02 17:34
PhpStorm 2017.1.4
Build #PS-171.4694.2, built on May 16, 2017

Switching via File → Open Recent.

**Comment by kalessil** [comment] 2017-06-09 13:13
Can not reproduce, getting thru codebase to see any suspicious fragments.

**Comment by kalessil** [comment] 2018-02-28 18:29
Closing as was not able to reproduce

**Closed by kalessil** 2018-02-28 18:29 UTC
